# Generated by Django 3.2.3 on 2021-05-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0002_auto_20210528_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catedra',
            options={'ordering': ['date_create'], 'verbose_name': 'Catedra', 'verbose_name_plural': 'Catedras'},
        ),
    ]
