# Generated by Django 3.2.3 on 2021-05-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0007_alter_catedra_date_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catedra',
            options={'ordering': ['-date_create'], 'verbose_name': 'Catedra', 'verbose_name_plural': 'Catedras'},
        ),
    ]
