# Generated by Django 3.2.3 on 2021-05-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0011_alter_catedra_date_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catedra',
            options={'verbose_name': 'Catedra', 'verbose_name_plural': 'Catedras'},
        ),
    ]
