# Generated by Django 3.2.3 on 2021-05-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0012_alter_catedra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['-date_create'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
