# Generated by Django 3.2.3 on 2021-05-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0013_alter_categorias_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
