# Generated by Django 3.2.3 on 2021-05-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0014_alter_categorias_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
