# Generated by Django 3.2.3 on 2021-05-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0016_auto_20210529_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
