# Generated by Django 3.2.3 on 2021-05-30 22:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0018_alter_catedra_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción'),
        ),
    ]
