# Generated by Django 3.2.3 on 2021-07-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0020_auto_20210721_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedra',
            name='contact_number',
            field=models.TimeField(blank=True, null=True, verbose_name='Escribemos:'),
        ),
    ]
