# Generated by Django 3.2.3 on 2021-07-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0022_catedra_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Escribemos:'),
        ),
    ]
