# Generated by Django 3.2.3 on 2021-07-25 01:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0023_alter_catedra_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedra',
            name='cathedra',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Docente:'),
        ),
        migrations.AddField(
            model_name='catedra',
            name='profit',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Docente:'),
        ),
        migrations.AddField(
            model_name='catedra',
            name='syllabus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='catedra',
            name='speaker',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Docente:'),
        ),
    ]
