# Generated by Django 3.2.3 on 2021-07-25 18:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0024_auto_20210724_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catedra',
            name='speaker',
        ),
        migrations.AlterField(
            model_name='catedra',
            name='cathedra',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='El enfoque de aprendizaje de Cátedra:'),
        ),
        migrations.AlterField(
            model_name='catedra',
            name='profit',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Beneficios:'),
        ),
        migrations.AlterField(
            model_name='catedra',
            name='syllabus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Plan de estudios'),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Docente')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foto-ponente/', verbose_name='Portada')),
                ('catedra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catedra.catedra')),
            ],
            options={
                'verbose_name': 'Datos del docente',
                'verbose_name_plural': 'Datos de los docentes',
            },
        ),
    ]
