# Generated by Django 3.2.3 on 2021-08-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catedra', '0027_alter_catedra_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Escribenos:'),
        ),
    ]
