# Generated by Django 3.2.3 on 2021-06-09 22:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_alter_author_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción')),
                ('photo', models.ImageField(upload_to='actualidades/', verbose_name='Fotografía')),
                ('state', models.BooleanField(default=True, verbose_name='Activo/No activo')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Actualidad',
                'verbose_name_plural': 'Actualidades',
                'ordering': ['-date_create'],
            },
        ),
    ]
