# Generated by Django 3.2.3 on 2021-07-25 23:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualidades',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='acctualidades-pdf/', verbose_name='Archivo PDF'),
        ),
        migrations.AddField(
            model_name='actualidades',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
