# Generated by Django 3.2.3 on 2021-08-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualidades', '0003_auto_20210819_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualidades',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Subtítulo'),
        ),
    ]
