# Generated by Django 3.2.3 on 2021-08-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualidades', '0004_alter_actualidades_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualidades',
            name='links',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Fuente:'),
        ),
    ]
