# Generated by Django 3.2.3 on 2021-09-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Título')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Descripción imagen de fondo')),
                ('image_background', models.ImageField(upload_to='firma/', verbose_name='Imagen de fondo')),
                ('partner', models.TextField(blank=True, null=True, verbose_name='Descripción socio fundador')),
                ('image_partner', models.ImageField(upload_to='firma/', verbose_name='Imagen de socio fundador')),
                ('value_firma', models.TextField(blank=True, null=True, verbose_name='Descripción de Valores')),
                ('responsibility_firma', models.TextField(blank=True, null=True, verbose_name='Descripción de Responsabilidad social')),
                ('red_firma', models.TextField(blank=True, null=True, verbose_name='Descripción de Red Internacional')),
            ],
            options={
                'verbose_name': 'Firma',
            },
        ),
    ]
