# Generated by Django 3.2.3 on 2021-09-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firma'},
        ),
        migrations.AddField(
            model_name='firma',
            name='description_founder',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción fundador'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
