# Generated by Django 3.2.3 on 2021-06-01 15:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='photo',
            field=models.ImageField(upload_to='equipo/', verbose_name='Fotografía'),
        ),
    ]
