# Generated by Django 3.2.3 on 2021-06-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_auto_20210601_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['date_create'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grado académico'),
        ),
    ]
