# Generated by Django 3.2.3 on 2021-06-05 21:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='summary',
            field=ckeditor.fields.RichTextField(verbose_name='Resumen'),
        ),
    ]
