# Generated by Django 3.2.3 on 2021-08-20 02:00

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_alter_publicaciones_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='photo',
            field=models.ImageField(upload_to='publicaciones/', verbose_name='Imagen de publicación'),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='summary',
            field=ckeditor.fields.RichTextField(verbose_name='Subtítulo'),
        ),
    ]
