# Generated by Django 3.2.3 on 2021-08-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_auto_20210819_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='summary',
            field=models.TextField(verbose_name='Subtítulo'),
        ),
    ]
